plugins {
    id 'fabric-loom' apply false
    id 'maven-publish'
}

// Apply common config to all subprojects that need Fabric
subprojects {
    apply plugin: 'fabric-loom'
    apply plugin: 'maven-publish'

    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        mavenCentral()
        maven { url = "https://maven.fabricmc.net/" }
    }

    loom {
        mods {
            "datalib" {
                sourceSet sourceSets.main
            }
        }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.officialMojangMappings()
        modImplementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"
        modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_version}"
    }

    processResources {
        inputs.property "version", project.version
        filesMatching("fabric.mod.json") {
            expand "version": project.version
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    java {
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    jar {
        from(rootProject.file("LICENSE")) {
            rename { "${it}_${project.name}" }
        }
    }

    publishing {
        publications {
            create("mavenJava", MavenPublication) {
                from components.java
            }
        }
    }
}
