base {
    archivesName = "datalib-main"
}

dependencies {
    modImplementation project(path: ":core", configuration: "namedElements")
    modImplementation project(path: ":command", configuration: "namedElements")
    modImplementation project(path: ":log", configuration: "namedElements")
}

tasks.jar {
    dependsOn(
        ":core:remapJar",
        ":command:remapJar",
        ":log:remapJar"
    )

    from(zipTree(project(":core").tasks.named("remapJar").get().archiveFile)) {
        into("META-INF/jars")
        rename { "datalib-core.jar" }
    }

    from(zipTree(project(":command").tasks.named("remapJar").get().archiveFile)) {
        into("META-INF/jars")
        rename { "datalib-command.jar" }
    }

    from(zipTree(project(":log").tasks.named("remapJar").get().archiveFile)) {
        into("META-INF/jars")
        rename { "datalib-log.jar" }
    }
}
